# Banjo-Kazooie's n_aspMain
text_offset = 0xF4DDC0
text_size = 0xC60
text_address = 0x04001080
rom_file_path = "banjo.us.v10.decompressed.z64"
output_file_path = "rsp/n_aspMain.cpp"
output_function_name = "n_aspMain" 
extra_indirect_branch_targets = [
    # dispatch table
    0x10F0, 0x13A0, 0x11A0, 0x1A68, 0x11CC, 0x17F0, 0x120C, 0x1280, 0x134C, 0x124C, 0x1C88, 0x12D8, 0x12B0, 0x1388
]
